# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-18 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standby', models.CharField(blank=True, max_length=200, null=True, verbose_name='备用字段')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='通知时间')),
                ('is_dispose', models.BooleanField(default=False, verbose_name='是否处理')),
                ('is_active', models.BooleanField(default=True, verbose_name='状态')),
            ],
        ),
    ]
