# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-18 10:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_myinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='myinformation',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='information_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
