# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-16 17:01
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20, verbose_name='类别')),
                ('class_two_id', models.IntegerField(verbose_name='二级id')),
                ('is_active', models.BooleanField(default=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '图书类别',
                'verbose_name_plural': '图书类别',
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=500, verbose_name='图书名字')),
                ('author', models.CharField(blank=True, max_length=500, null=True, verbose_name='作者')),
                ('press', models.CharField(blank=True, max_length=100, null=True, verbose_name='出版社')),
                ('press_time', models.CharField(blank=True, max_length=100, null=True, verbose_name='出版日期')),
                ('price', models.IntegerField(blank=True, default=20, null=True, verbose_name='价格（书香豆）')),
                ('all_number_book', models.IntegerField(blank=True, default=30, null=True, verbose_name='书本总数量')),
                ('surplus_number_book', models.IntegerField(blank=True, default=30, null=True, verbose_name='剩余数量')),
                ('check_number', models.IntegerField(blank=True, default=0, null=True, verbose_name='查看次数')),
                ('borrow_number', models.IntegerField(blank=True, default=0, null=True, verbose_name='借阅次数')),
                ('booking_number', models.IntegerField(blank=True, default=0, null=True, verbose_name='在线阅读次数')),
                ('credit_value', models.IntegerField(blank=True, default=100, null=True, verbose_name='所需信用值')),
                ('intro', models.TextField(blank=True, null=True, verbose_name='简介')),
                ('image', models.ImageField(blank=True, default='photo/default.jpg', null=True, upload_to='photo', verbose_name='图片')),
                ('is_active', models.BooleanField(default=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '书籍',
                'verbose_name_plural': '书籍',
            },
        ),
        migrations.CreateModel(
            name='BorrowBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default=1, max_length=20, verbose_name='收货地址id')),
                ('start_time', models.DateField(default=datetime.date.today, verbose_name='起始时间')),
                ('end_time', models.DateField(verbose_name='结束时间')),
                ('borrow_time', models.IntegerField(blank=True, null=True, verbose_name='时长')),
                ('is_give_back', models.BooleanField(default=False, verbose_name='是否归还')),
                ('is_exceed_time', models.BooleanField(default=False, verbose_name='是否超期')),
                ('is_active', models.BooleanField(default=True, verbose_name='状态')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_book', to='bookapp.Books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '借阅书籍信息',
                'verbose_name_plural': '借阅书籍信息',
            },
        ),
        migrations.CreateModel(
            name='UserBookComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='评论时间')),
                ('comment', models.TextField(verbose_name='评论')),
                ('is_active', models.BooleanField(default=True, verbose_name='状态')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_book', to='bookapp.Books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.AddField(
            model_name='bookclasses',
            name='book',
            field=models.ManyToManyField(related_name='book_class', to='bookapp.Books'),
        ),
    ]
